### ISSUE TITLE
Possible to publish the different API versions as extras, instead?

### ISSUE THREAD

**Issue by ferdnyc** [pygobject/pygobject-stubs#161]
I was just wondering, as I came here to once again look up the correct install incantation to properly install the _correct versions_ of the type stubs into a given project:

Is there any way anyone can think of, that the differently-versioned stubs for a given module could be published as package **extras**, instead of build configuration options?

Beyond making `pygobject-stubs` easier to install...

```bash
# No longer this...
PYGOBJECT_STUB_CONFIG=Gtk3,Gdk3,Soup2 \
pip install pygobject-stubs --no-cache-dir

# Or this...
pip install pygobject-stubs --no-cache-dir \
--config-settings=config=Gtk3,Gdk3,Soup2

# But instead, this...
pip install 'pygobject-stubs[Gtk3,Gdk3,Soup2]'
```

The _real_ win would be that projects _using_ the various GObject modules could **include them directly in their development dependencies list**, with the versions already preselected to match the project code. (No more grepping a project's code for `require_version` just to determine all of the module versions that need to be defined for the `pygobject-stubs` install.)

Right now, there's no point in listing `pygobject-stubs` in a project's dependencies, because it'll be installed incorrectly without the configuration envvar/argument.

I'm not even sure it's possible (I certainly don't have any ideas how to make it work), but I'm not 100% sure it's **IM-possible** either. So I figured I'd throw it out there for brainstorming.

**Comment by ferdnyc** [comment]
(Even if each module's stubs had to be published as a separate package, `pygobject-<foo><version#>-stubs` — so `pygobject-gtk3-stubs`, `pygobject-gdk4-stubs`, etc. — in order that they could be pulled in to the overall `pygobject-stubs` package as extras, it might be worth it.)

**Comment by lovetox** [comment]
extras install different packages and not modify a existing package.

type checkers only look in one single package for stubs, `pygobject-stubs`.

if the files are not in this package they will not be picked up.

Other packages cannot "extend" the package in a way that they copy files into another package.

if you use a requirements file with pip, you can already put `config-settings` per requirement line.

So as a workaround maybe use a requirements file for installing dev dependencies

**Comment by lovetox** [comment]
I updated the README with this approach.
I think this is the best you can do at the moment.

What would be even better is, if the pyproject.toml spec would allow to pass `config-settings` per requirement.
But i don’t think the spec does currently allow it. Maybe raise an issue on the python tracker? I think its a gap currently.

Installing development dependencies via requirements file is an acceptable workaround, that allows you to maintain the dependencies within the project as code and allows the user to install them without knowing the details.

I dont think we can do any more within this project to make that easier. None of your brainstormed ideas are new, but none of them would work, because stubs need to be very specific packaged otherwise type checkers will not pick them up.
