### ISSUE TITLE
Encode version info in the import

### ISSUE THREAD

**Issue by lazka** [pygobject/pygobject-stubs#3]
require_version doesn't work, we need to switch stubs based on the import name

e.g. `from gi.repository import Gtk_3_0 as Gtk`

There also is `if typing.TYPE_CHECKING:` so we can play with this without having to change pygobject

**Comment by lovetox** [comment]
Other solutions for the version problem i thought of was

Provide some kind of install flag which can be passed to pip or setup.py? --gtkversion=3
and then we install only these stubs.

Python developers probably uses some kind of venv anyway and that would not be a problem to have the stubs installed in a special configuration.

further checking is often done in CI, and there its probably even less of a problem.

I don’t understand how your approach with versioned imports can work.
This would fail because pygobject does not allow such an import or are you saying you would add this to pygobject?

if not supported by pygobject then something like this would still work

```python
import typing

if typing.TYPE_CHECKING:
    from gi.repository import Gtk_3_0 as Gtk
else:
    from gi.repository import Gtk
```

but of course this is not very sexy

if you wonder if this works

```python
import typing

from gi.repository import Gtk
if typing.TYPE_CHECKING:
    from gi.repository import Gtk_3_0 as Gtk
```

no it does not. mypy does not overwrite that first import

**Comment by MrinmoyHaloi** [comment]
Can't we make different packages for different versions. Like PyGobject-stubs-3, PyGobject-stubs-4. It might solve the problem. @lovetox

**Comment by lovetox** [comment]
no because this is not a Gtk stub package, its a stub package for all libraries where PyGObject provides bindings.

So PyGObject-stubs-3 means nothing.

Of course one could factor out all libraries into different stub packages

pygobject-gtk3-stubs
pygobject-glib-stubs
pygobject-libsoup-stubs

as most developers going to be using only a few of the libraries anyway, and the code paths for the different stubs need to be separated anyway, i see no benefit in having all of them in one package. Except of course there is a big amount of libraries and so a big amount of repositories to maintain.

Maybe a compromise would be to do it only for the libraries where we expect old versions to be used for years, like with gtk.

so only splitting out gtk for now.

**Comment by MrinmoyHaloi** [comment]
19 repositories total. That will be very hard to maintain. We should split out gtk out of it. It will be easier to maintain

**Comment by MrinmoyHaloi** [comment]
And also i think maintaining different package for different versions of gtk would easier then doing all versions in one package

**Comment by lazka** [comment]
I don't think there can be more than one stub package for another Python package, if I'm reading https://peps.python.org/pep-0561/ correctly.

**Comment by lovetox** [comment]
ah damn, i forgot we import all from the gi namespace, that seems indeed not possible.

then im back to my suggestion with doing install magic with install flags

**Comment by MrinmoyHaloi** [comment]
I dont think we can pass flags to pip during installation @lovetox

**Comment by MrinmoyHaloi** [comment]
We need to change the way we import namespaces. Instead of gtk namespace there can  be gtk3 and gtk4 namespace. As said by @lazka.  And also before making the stubs the main pygobject package should be worked on. The documentation should be updated to gtk4. I dont think people will start using stubs for gtk4 before learning how to use gtk4.

**Comment by lovetox** [comment]
What lazka proposed is other projects that use the stubs import the stubs in a different way. This would actually force all projects to change all their gtk imports. Further as i said above it does not work without also changing pygobject itself.

As i see it we can pass flags via `--install-option'' command when the package gets installed.
This would allow anyone to decide themself what gets installed.

so `pip install pygobject-stubs --install-options="--gtkversion=3"`

**Comment by lovetox** [comment]
I added a PR that is a PoC for what i suggested.
This allows developers who install to choose the lib versions they need

I would go the way to install the most current lib when no options are provided, for example Gtk4 currently.

Drawback with that solution is that this makes it hard for distributions to package, but as this is a developer package, i guess we can live with that.

Im open for better solutions if anyone has an idea

**Comment by MrinmoyHaloi** [comment]
Looks great. @lovetox.
