### ISSUE TITLE
generate.py script output is different, and lacking, compared to stubs included in the repo

### ISSUE THREAD

**Issue by 1player** [pygobject/pygobject-stubs#45]
I'm trying to manually create the stubs for Gtk 4, but I've noticed that the generate.py script included in the repo lacks a ton of critical information compared to the stubs included in the repo.

When comparing locally generated stubs with the repo, I see that:

* imports are missing
* many types on root level functions are missing
* base class information is missing

Basically locally generated stubs are useless for type checking. 

Is the script out of date? How can I recreate those `*.pyi` files on my machine, so that they include all the information present in this repo?

**Comment by lovetox** [comment]
This script is for developers to get a starting point for typing.
So that you don't have to extract all methods and classes manually.

Its not intended to be used as stubs itself.

There is no way currently to generate stubs automatically, its all work from contributors.

I will make this in the README more clear
