### ISSUE TITLE
Generate code automatically via tools provided by JetBrains?

### ISSUE THREAD

**Issue by gzxu** [pygobject/pygobject-stubs#5]
```sh
git clone --depth 1 https://github.com/JetBrains/intellij-community.git /tmp/idea
mkdir /tmp/out
for typelib in Atk GLib GModule GObject Gdk GdkPixbuf Gio Gtk Pango; do
    python3 /tmp/idea/python/helpers/generator3.py -d /tmp/out -x gi.repository.$typelib $(python3 -c "from gi.repository import $typelib; print($typelib.__path__[-1])")
done
```

And stubs can be found under `/tmp/out`. Currently this repository seems to be much incomplete?

**Comment by lazka** [comment]
Yeah, it's work in progress: https://github.com/pygobject/pgi-docgen/pull/176

**Comment by AdamVerner** [comment]
what about [Fakegir](https://github.com/strycore/fakegir)?

**Comment by ju1ius** [comment]
@AdamVerner Fakegir generates stubs from gir xml files, while the JetBrains tool generates them by doing a runtime introspection. Last time I checked, the stubs generated by the JetBrains tool were way more exhaustive and accurate.

**Comment by ttys3** [comment]
> /tmp/out

year 2020 now, still find you tips works fine with litlte mod:

```bash
git clone --depth 1 https://github.com/JetBrains/intellij-community.git /tmp/idea
mkdir /tmp/out
for typelib in Atk GLib GModule GObject Gdk GdkPixbuf Gio Gtk Pango; do
    python3  /tmp/idea/python/helpers/generator3/__main__.py -d /tmp/out -p gi.repository.$typelib $(python3 -c "import gi; gi.require_versions({'Atk': '1.0', 'GModule': '2.0', 'Gdk': '3.0', 'GdkPixbuf': '2.0', 'Gtk': '3.0', 'Pango': '1.0'}); from gi.repository import $typelib; print($typelib.__path__[-1])")
done
```

but there's little troubleshoot: 
we need let `generator3` run `gi.require_versions({'Atk': '1.0', 'GModule': '2.0', 'Gdk': '3.0', 'GdkPixbuf': '2.0', 'Gtk': '3.0', 'Pango': '1.0'})` before using the `$typelib`

otherwise there will be a warning:
`PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.`

anyway, the generated stubs works quite well, in my word, it is better than `PyGObject-stubs`.
since PyGObject-stubs provides no param info.

**Comment by ttys3** [comment]
update:

I’ve make a new repo and pushed the auto generated stubs:

https://github.com/ttys3/pygobject-stubs

**Comment by dsvensson** [comment]
@ttys3 are these supposed to work with pyright?

**Comment by danyeaw** [comment]
@lazka What do you think about merging @ttys3's fork so that we can have a new PyPI release?

**Comment by lovetox** [comment]
I will close this, stubs like this can be generated with generate script in this repo for modules which users need. Apart from that the real signatures have to be added manually.
