### ISSUE TITLE
May we bump up the pygobject-stubs version (to 2.0.0 for example) to make gtk4 the default gtk version?

### ISSUE THREAD

**Issue by wsgalaxy** [pygobject/pygobject-stubs#68]
gtk3 is very stable now, the one who need gtk3 stub files can stick to pygobject-stubs 1.0.0 while the others could use the latest version for gtk4.

**Comment by wsgalaxy** [comment]
The other option is to provide something like "pygobject-stubs-gtk4" or "pygobject-stubs-next" to make gtk4 the default version in gi-stubs, and then make this package conflict with the original pygobject-stubs. The one who need gtk4 support just need to install pygobject-stubs-next.

**Comment by lovetox** [comment]
1. this is not a GTK stubs library, it has stubs for all pygobject compatible projects, GTK is only a single one of them.
2. It does not matter how stable GTK3 is, because the stubs in this project for GTK3 are not complete so we need to further develop it
3. Ideas are discussed at https://github.com/pygobject/pygobject-stubs/issues/3
